// Mocks generated by Mockito 5.4.6 from annotations
// in geo_valid_app/test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i8;

import 'package:geo_valid_app/features/auth/data/auth_repository.dart' as _i2;
import 'package:geo_valid_app/features/chatbot/data/chat_model_type.dart'
    as _i5;
import 'package:geo_valid_app/features/chatbot/data/chat_repository.dart'
    as _i4;
import 'package:geo_valid_app/features/detection/data/detection_repository.dart'
    as _i7;
import 'package:geo_valid_app/features/home/data/feed_item.dart' as _i11;
import 'package:geo_valid_app/features/home/data/home_repository.dart' as _i10;
import 'package:geo_valid_app/features/profile/data/profile_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> register({
    required String? email,
    required String? password,
    required String? username,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #password: password,
            #username: username,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> googleSignIn() => (super.noSuchMethod(
        Invocation.method(
          #googleSignIn,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i4.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> sendMessage(
    String? question,
    _i5.ChatModelType? modelType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            question,
            modelType,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #sendMessage,
            [
              question,
              modelType,
            ],
          ),
        )),
      ) as _i3.Future<String>);
}

/// A class which mocks [DetectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetectionRepository extends _i1.Mock
    implements _i7.DetectionRepository {
  MockDetectionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> uploadImageToStorage(
    _i8.File? file,
    String? folder,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImageToStorage,
          [
            file,
            folder,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImageToStorage,
            [
              file,
              folder,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> uploadBase64ToStorage(
    String? base64String,
    String? folder,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBase64ToStorage,
          [
            base64String,
            folder,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadBase64ToStorage,
            [
              base64String,
              folder,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<Map<String, dynamic>> analyzeImage(_i8.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeImage,
          [imageFile],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> checkLocationRisk(
    double? lat,
    double? long,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkLocationRisk,
          [
            lat,
            long,
          ],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> saveDetectionResult({
    required double? latitude,
    required double? longitude,
    required String? originalImageUrl,
    required String? overlayImageUrl,
    required String? maskImageUrl,
    required String? detectionResult,
    required String? statusLevel,
    required Map<String, dynamic>? descriptionMap,
    required String? address,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDetectionResult,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #originalImageUrl: originalImageUrl,
            #overlayImageUrl: overlayImageUrl,
            #maskImageUrl: maskImageUrl,
            #detectionResult: detectionResult,
            #statusLevel: statusLevel,
            #descriptionMap: descriptionMap,
            #address: address,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i9.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> sendFeedback(String? content) => (super.noSuchMethod(
        Invocation.method(
          #sendFeedback,
          [content],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> uploadAvatar(
    _i8.File? file,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [
            file,
            userId,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAvatar,
            [
              file,
              userId,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateProfile({
    String? username,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #username: username,
            #avatarUrl: avatarUrl,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> changePassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {
            #oldPassword: oldPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i10.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i11.FeedItem>> fetchDetections({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDetections,
          [],
          {#page: page},
        ),
        returnValue: _i3.Future<List<_i11.FeedItem>>.value(<_i11.FeedItem>[]),
      ) as _i3.Future<List<_i11.FeedItem>>);

  @override
  _i3.Future<List<_i11.FeedItem>> fetchBMKG() => (super.noSuchMethod(
        Invocation.method(
          #fetchBMKG,
          [],
        ),
        returnValue: _i3.Future<List<_i11.FeedItem>>.value(<_i11.FeedItem>[]),
      ) as _i3.Future<List<_i11.FeedItem>>);
}
